name: linqup_mobile_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  google_maps_flutter: ^2.10.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/png/ball.png
    - assets/png/delete.png
    - assets/png/nigeria.png
    - assets/png/tree.png
    - assets/png/like.png
    - assets/png/message.png
    - assets/png/share.png
    - assets/png/rectangle_controller.png
    - assets/png/LinQup.png
    - assets/png/linqup_logo.png
    - assets/png/notification.png
    - assets/png/plus.png
    - assets/png/pda.png
    - assets/jpg/couple.jpg
    - assets/jpg/city.jpg
    - assets/jpg/profile2.jpg
    - assets/jpg/profile.jpeg
    - assets/jpg/women1.jpg
    - assets/jpg/women2.jpg
    - assets/jpg/women3.jpg
    - assets/jpg/women4.jpg
    - assets/jpg/women5.jpg

    # This is the path to assets
    - assets/png/
